<?php 


function ctsc_metadata_columns(){
	return array(
	1 => 1,
	2 => 2,
	3 => 3,
	4 => 4,
	5 => 5,
	6 => 6,
	);
}

function ctsc_metadata_orderby(){
	return array(
	'By Date' => 'date',
	'By Modified Date' => 'modified',
	'By Title' => 'title',
	'By Menu Order' => 'menu_order',
	'By Author' => 'author',
	'By ID' => 'ID',
	'Random Order' => 'rand',
	);
}


function ctsc_metadata_order(){
	return array(
	'Descending Order' => 'DESC',
	'Ascending Order' => 'ASC',
	);
}


function ctsc_metadata_icons(){
	$ctsc_data = array(	
	'0' => __('(None)', 'ctsc'),
	'glass' => '&#xf000; glass',
	'music' => '&#xf001; music',
	'search' => '&#xf002; search',
	'envelope' => '&#xf003; envelope',
	'heart' => '&#xf004; heart',
	'star' => '&#xf005; star',
	'star-empty' => '&#xf006; star-empty',
	'user' => '&#xf007; user',
	'film' => '&#xf008; film',
	'th-large' => '&#xf009; th-large',
	'th' => '&#xf00a; th',
	'th-list' => '&#xf00b; th-list',
	'ok' => '&#xf00c; ok',
	'remove' => '&#xf00d; remove',
	'zoom-in' => '&#xf00e; zoom-in',
	'zoom-out' => '&#xf010; zoom-out',
	'off' => '&#xf011; off',
	'signal' => '&#xf012; signal',
	'cog' => '&#xf013; cog',
	'trash' => '&#xf014; trash',
	'home' => '&#xf015; home',
	'file' => '&#xf016; file',
	'time' => '&#xf017; time',
	'road' => '&#xf018; road',
	'download-alt' => '&#xf019; download-alt',
	'download' => '&#xf01a; download',
	'upload' => '&#xf01b; upload',
	'inbox' => '&#xf01c; inbox',
	'play-circle' => '&#xf01d; play-circle',
	'repeat' => '&#xf01e; repeat',
	'refresh' => '&#xf021; refresh',
	'list-alt' => '&#xf022; list-alt',
	'lock' => '&#xf023; lock',
	'flag' => '&#xf024; flag',
	'headphones' => '&#xf025; headphones',
	'volume-off' => '&#xf026; volume-off',
	'volume-down' => '&#xf027; volume-down',
	'volume-up' => '&#xf028; volume-up',
	'qrcode' => '&#xf029; qrcode',
	'barcode' => '&#xf02a; barcode',
	'tag' => '&#xf02b; tag',
	'tags' => '&#xf02c; tags',
	'book' => '&#xf02d; book',
	'bookmark' => '&#xf02e; bookmark',
	'print' => '&#xf02f; print',
	'camera' => '&#xf030; camera',
	'font' => '&#xf031; font',
	'bold' => '&#xf032; bold',
	'italic' => '&#xf033; italic',
	'text-height' => '&#xf034; text-height',
	'text-width' => '&#xf035; text-width',
	'align-left' => '&#xf036; align-left',
	'align-center' => '&#xf037; align-center',
	'align-right' => '&#xf038; align-right',
	'align-justify' => '&#xf039; align-justify',
	'list' => '&#xf03a; list',
	'indent-left' => '&#xf03b; indent-left',
	'indent-right' => '&#xf03c; indent-right',
	'facetime-video' => '&#xf03d; facetime-video',
	'picture' => '&#xf03e; picture',
	'pencil' => '&#xf040; pencil',
	'map-marker' => '&#xf041; map-marker',
	'adjust' => '&#xf042; adjust',
	'tint' => '&#xf043; tint',
	'edit' => '&#xf044; edit',
	'share' => '&#xf045; share',
	'check' => '&#xf046; check',
	'move' => '&#xf047; move',
	'step-backward' => '&#xf048; step-backward',
	'fast-backward' => '&#xf049; fast-backward',
	'backward' => '&#xf04a; backward',
	'play' => '&#xf04b; play',
	'pause' => '&#xf04c; pause',
	'stop' => '&#xf04d; stop',
	'forward' => '&#xf04e; forward',
	'fast-forward' => '&#xf050; fast-forward',
	'step-forward' => '&#xf051; step-forward',
	'eject' => '&#xf052; eject',
	'chevron-left' => '&#xf053; chevron-left',
	'chevron-right' => '&#xf054; chevron-right',
	'plus-sign' => '&#xf055; plus-sign',
	'minus-sign' => '&#xf056; minus-sign',
	'remove-sign' => '&#xf057; remove-sign',
	'ok-sign' => '&#xf058; ok-sign',
	'question-sign' => '&#xf059; question-sign',
	'info-sign' => '&#xf05a; info-sign',
	'screenshot' => '&#xf05b; screenshot',
	'remove-circle' => '&#xf05c; remove-circle',
	'ok-circle' => '&#xf05d; ok-circle',
	'ban-circle' => '&#xf05e; ban-circle',
	'arrow-left' => '&#xf060; arrow-left',
	'arrow-right' => '&#xf061; arrow-right',
	'arrow-up' => '&#xf062; arrow-up',
	'arrow-down' => '&#xf063; arrow-down',
	'share-alt' => '&#xf064; share-alt',
	'resize-full' => '&#xf065; resize-full',
	'resize-small' => '&#xf066; resize-small',
	'plus' => '&#xf067; plus',
	'minus' => '&#xf068; minus',
	'asterisk' => '&#xf069; asterisk',
	'exclamation-sign' => '&#xf06a; exclamation-sign',
	'gift' => '&#xf06b; gift',
	'leaf' => '&#xf06c; leaf',
	'fire' => '&#xf06d; fire',
	'eye-open' => '&#xf06e; eye-open',
	'eye-close' => '&#xf070; eye-close',
	'warning-sign' => '&#xf071; warning-sign',
	'plane' => '&#xf072; plane',
	'calendar' => '&#xf073; calendar',
	'random' => '&#xf074; random',
	'comment' => '&#xf075; comment',
	'magnet' => '&#xf076; magnet',
	'chevron-up' => '&#xf077; chevron-up',
	'chevron-down' => '&#xf078; chevron-down',
	'retweet' => '&#xf079; retweet',
	'shopping-cart' => '&#xf07a; shopping-cart',
	'folder-close' => '&#xf07b; folder-close',
	'folder-open' => '&#xf07c; folder-open',
	'resize-vertical' => '&#xf07d; resize-vertical',
	'resize-horizontal' => '&#xf07e; resize-horizontal',
	'bar-chart' => '&#xf080; bar-chart',
	'twitter-sign' => '&#xf081; twitter-sign',
	'facebook-sign' => '&#xf082; facebook-sign',
	'camera-retro' => '&#xf083; camera-retro',
	'key' => '&#xf084; key',
	'cogs' => '&#xf085; cogs',
	'comments' => '&#xf086; comments',
	'thumbs-up' => '&#xf087; thumbs-up',
	'thumbs-down' => '&#xf088; thumbs-down',
	'star-half' => '&#xf089; star-half',
	'heart-empty' => '&#xf08a; heart-empty',
	'signout' => '&#xf08b; signout',
	'linkedin-sign' => '&#xf08c; linkedin-sign',
	'pushpin' => '&#xf08d; pushpin',
	'external-link' => '&#xf08e; external-link',
	'signin' => '&#xf090; signin',
	'trophy' => '&#xf091; trophy',
	'github-sign' => '&#xf092; github-sign',
	'upload-alt' => '&#xf093; upload-alt',
	'lemon' => '&#xf094; lemon',
	'phone' => '&#xf095; phone',
	'check-empty' => '&#xf096; check-empty',
	'bookmark-empty' => '&#xf097; bookmark-empty',
	'phone-sign' => '&#xf098; phone-sign',
	'twitter' => '&#xf099; twitter',
	'facebook' => '&#xf09a; facebook',
	'github' => '&#xf09b; github',
	'unlock' => '&#xf09c; unlock',
	'credit-card' => '&#xf09d; credit-card',
	'rss' => '&#xf09e; rss',
	'hdd' => '&#xf0a0; hdd',
	'bullhorn' => '&#xf0a1; bullhorn',
	'bell' => '&#xf0a2; bell',
	'certificate' => '&#xf0a3; certificate',
	'hand-right' => '&#xf0a4; hand-right',
	'hand-left' => '&#xf0a5; hand-left',
	'hand-up' => '&#xf0a6; hand-up',
	'hand-down' => '&#xf0a7; hand-down',
	'circle-arrow-left' => '&#xf0a8; circle-arrow-left',
	'circle-arrow-right' => '&#xf0a9; circle-arrow-right',
	'circle-arrow-up' => '&#xf0aa; circle-arrow-up',
	'circle-arrow-down' => '&#xf0ab; circle-arrow-down',
	'globe' => '&#xf0ac; globe',
	'wrench' => '&#xf0ad; wrench',
	'tasks' => '&#xf0ae; tasks',
	'filter' => '&#xf0b0; filter',
	'briefcase' => '&#xf0b1; briefcase',
	'fullscreen' => '&#xf0b2; fullscreen',
	'group' => '&#xf0c0; group',
	'link' => '&#xf0c1; link',
	'cloud' => '&#xf0c2; cloud',
	'beaker' => '&#xf0c3; beaker',
	'cut' => '&#xf0c4; cut',
	'copy' => '&#xf0c5; copy',
	'paper-clip' => '&#xf0c6; paper-clip',
	'save' => '&#xf0c7; save',
	'sign-blank' => '&#xf0c8; sign-blank',
	'reorder' => '&#xf0c9; reorder',
	'list-ul' => '&#xf0ca; list-ul',
	'list-ol' => '&#xf0cb; list-ol',
	'strikethrough' => '&#xf0cc; strikethrough',
	'underline' => '&#xf0cd; underline',
	'table' => '&#xf0ce; table',
	'magic' => '&#xf0d0; magic',
	'truck' => '&#xf0d1; truck',
	'pinterest' => '&#xf0d2; pinterest',
	'pinterest-sign' => '&#xf0d3; pinterest-sign',
	'google-plus-sign' => '&#xf0d4; google-plus-sign',
	'google-plus' => '&#xf0d5; google-plus',
	'money' => '&#xf0d6; money',
	'caret-down' => '&#xf0d7; caret-down',
	'caret-up' => '&#xf0d8; caret-up',
	'caret-left' => '&#xf0d9; caret-left',
	'caret-right' => '&#xf0da; caret-right',
	'columns' => '&#xf0db; columns',
	'sort' => '&#xf0dc; sort',
	'sort-down' => '&#xf0dd; sort-down',
	'sort-up' => '&#xf0de; sort-up',
	'envelope-alt' => '&#xf0e0; envelope-alt',
	'linkedin' => '&#xf0e1; linkedin',
	'undo' => '&#xf0e2; undo',
	'legal' => '&#xf0e3; legal',
	'dashboard' => '&#xf0e4; dashboard',
	'comment-alt' => '&#xf0e5; comment-alt',
	'comments-alt' => '&#xf0e6; comments-alt',
	'bolt' => '&#xf0e7; bolt',
	'sitemap' => '&#xf0e8; sitemap',
	'umbrella' => '&#xf0e9; umbrella',
	'paste' => '&#xf0ea; paste',
	'lightbulb' => '&#xf0eb; lightbulb',
	'exchange' => '&#xf0ec; exchange',
	'cloud-download' => '&#xf0ed; cloud-download',
	'cloud-upload' => '&#xf0ee; cloud-upload',
	'user-md' => '&#xf0f0; user-md',
	'stethoscope' => '&#xf0f1; stethoscope',
	'suitcase' => '&#xf0f2; suitcase',
	'bell-alt' => '&#xf0f3; bell-alt',
	'coffee' => '&#xf0f4; coffee',
	'food' => '&#xf0f5; food',
	'file-alt' => '&#xf0f6; file-alt',
	'building' => '&#xf0f7; building',
	'hospital' => '&#xf0f8; hospital',
	'ambulance' => '&#xf0f9; ambulance',
	'medkit' => '&#xf0fa; medkit',
	'fighter-jet' => '&#xf0fb; fighter-jet',
	'beer' => '&#xf0fc; beer',
	'h-sign' => '&#xf0fd; h-sign',
	'plus-sign-alt' => '&#xf0fe; plus-sign-alt',
	'double-angle-left' => '&#xf100; double-angle-left',
	'double-angle-right' => '&#xf101; double-angle-right',
	'double-angle-up' => '&#xf102; double-angle-up',
	'double-angle-down' => '&#xf103; double-angle-down',
	'angle-left' => '&#xf104; angle-left',
	'angle-right' => '&#xf105; angle-right',
	'angle-up' => '&#xf106; angle-up',
	'angle-down' => '&#xf107; angle-down',
	'desktop' => '&#xf108; desktop',
	'laptop' => '&#xf109; laptop',
	'tablet' => '&#xf10a; tablet',
	'mobile-phone' => '&#xf10b; mobile-phone',
	'circle-blank' => '&#xf10c; circle-blank',
	'quote-left' => '&#xf10d; quote-left',
	'quote-right' => '&#xf10e; quote-right',
	'spinner' => '&#xf110; spinner',
	'circle' => '&#xf111; circle',
	'reply' => '&#xf112; reply',
	'github-alt' => '&#xf113 github-alt',
	'folder-close-alt' => '&#xf114 folder-close-alt',
	'folder-open-alt' => '&#xf115 folder-open-alt',
	'expand-alt' => '&#xf116 expand-alt',
	'collapse-alt' => '&#xf117 collapse-alt',
	'smile' => '&#xf118 smile',
	'frown' => '&#xf119 frown',
	'meh' => '&#xf11a meh',
	'gamepad' => '&#xf11b gamepad',
	'keyboard' => '&#xf11c keyboard',
	'flag-alt' => '&#xf11d flag-alt',
	'flag-checkered' => '&#xf11e flag-checkered',
	'terminal' => '&#xf120 terminal',
	'code' => '&#xf121 code',
	'reply-all' => '&#xf122 reply-all',
	'mail-reply-all' => '&#xf122 mail-reply-all',
	'star-half-empty' => '&#xf123 star-half-empty',
	'location-arrow' => '&#xf124 location-arrow',
	'crop' => '&#xf125 crop',
	'code-fork' => '&#xf126 code-fork',
	'unlink' => '&#xf127 unlink',
	'question' => '&#xf128 question',
	'info' => '&#xf129 info',
	'exclamation' => '&#xf12a exclamation',
	'superscript' => '&#xf12b superscript',
	'subscript' => '&#xf12c subscript',
	'eraser' => '&#xf12d eraser',
	'puzzle-piece' => '&#xf12e puzzle-piece',
	'microphone' => '&#xf130 microphone',
	'microphone-off' => '&#xf131 microphone-off',
	'shield' => '&#xf132 shield',
	'calendar-empty' => '&#xf133 calendar-empty',
	'fire-extinguisher' => '&#xf134 fire-extinguisher',
	'rocket' => '&#xf135 rocket',
	'maxcdn' => '&#xf136 maxcdn',
	'chevron-sign-left' => '&#xf137 chevron-sign-left',
	'chevron-sign-right' => '&#xf138 chevron-sign-right',
	'chevron-sign-up' => '&#xf139 chevron-sign-up',
	'chevron-sign-down' => '&#xf13a chevron-sign-down',
	'html5' => '&#xf13b html5',
	'css3' => '&#xf13c css3',
	'anchor' => '&#xf13d anchor',
	'unlock-alt' => '&#xf13e unlock-alt',
	'bullseye' => '&#xf140 bullseye',
	'ellipsis-horizontal' => '&#xf141 ellipsis-horizontal',
	'ellipsis-vertical' => '&#xf142 ellipsis-vertical',
	'rss-sign' => '&#xf143 rss-sign',
	'play-sign' => '&#xf144 play-sign',
	'ticket' => '&#xf145 ticket',
	'minus-sign-alt' => '&#xf146 minus-sign-alt',
	'check-minus' => '&#xf147 check-minus',
	'level-up' => '&#xf148 level-up',
	'level-down' => '&#xf149 level-down',
	'check-sign' => '&#xf14a check-sign',
	'edit-sign' => '&#xf14b edit-sign',
	'external-link-sign' => '&#xf14c external-link-sign',
	'share-sign' => '&#xf14d share-sign',
	'compass' => '&#xf14e compass',
	'collapse' => '&#xf150 collapse',
	'collapse-top' => '&#xf151 collapse-top',
	'expand' => '&#xf152 expand',
	'eur' => '&#xf153 eur',
	'gbp' => '&#xf154 gbp',
	'usd' => '&#xf155 usd',
	'inr' => '&#xf156 inr',
	'jpy' => '&#xf157 jpy',
	'cny' => '&#xf158 cny',
	'krw' => '&#xf159 krw',
	'btc' => '&#xf15a btc',
	'file' => '&#xf15b file',
	'file-text' => '&#xf15c file-text',
	'sort-by-alphabet' => '&#xf15d sort-by-alphabet',
	'sort-by-alphabet-alt' => '&#xf15e sort-by-alphabet-alt',
	'sort-by-attributes' => '&#xf160 sort-by-attributes',
	'sort-by-attributes-alt' => '&#xf161 sort-by-attributes-alt',
	'sort-by-order' => '&#xf162 sort-by-order',
	'sort-by-order-alt' => '&#xf163 sort-by-order-alt',
	'thumbs-up' => '&#xf164 thumbs-up',
	'thumbs-down' => '&#xf165 thumbs-down',
	'youtube-sign' => '&#xf166 youtube-sign',
	'youtube' => '&#xf167 youtube',
	'xing' => '&#xf168 xing',
	'xing-sign' => '&#xf169 xing-sign',
	'youtube-play' => '&#xf16a youtube-play',
	'dropbox' => '&#xf16b dropbox',
	'stackexchange' => '&#xf16c stackexchange',
	'instagram' => '&#xf16d instagram',
	'flickr' => '&#xf16e flickr',
	'adn' => '&#xf170 adn',
	'bitbucket' => '&#xf171 bitbucket',
	'bitbucket-sign' => '&#xf172 bitbucket-sign',
	'tumblr' => '&#xf173 tumblr',
	'tumblr-sign' => '&#xf174 tumblr-sign',
	'long-arrow-down' => '&#xf175 long-arrow-down',
	'long-arrow-up' => '&#xf176 long-arrow-up',
	'long-arrow-left' => '&#xf177 long-arrow-left',
	'long-arrow-right' => '&#xf178 long-arrow-right',
	'apple' => '&#xf179 apple',
	'windows' => '&#xf17a windows',
	'android' => '&#xf17b android',
	'linux' => '&#xf17c linux',
	'dribbble' => '&#xf17d dribbble',
	'skype' => '&#xf17e skype',
	'foursquare' => '&#xf180 foursquare',
	'trello' => '&#xf181 trello',
	'female' => '&#xf182 female',
	'male' => '&#xf183 male',
	'gittip' => '&#xf184 gittip',
	'sun' => '&#xf185 sun',
	'moon' => '&#xf186 moon',
	'archive' => '&#xf187 archive',
	'bug' => '&#xf188 bug',
	'vk' => '&#xf189 vk',
	'weibo' => '&#xf18a weibo',
	'renren' => '&#xf18b renren');
	
	return $ctsc_data;
}


function ctsc_metadata_animation(){
	return array(
	'None' => '',
	'Zoom In' => 'zoomin',
	'Zoom Out' => 'zoomout',
	'Slide Up' => 'slideup',
	'Slide Down' => 'slidedown',
	'Slide Left' => 'slideleft',
	'Slide Right' => 'slideright',
	'Spin To The Left' => 'spinleft',
	'Spin To The Right' => 'spinright'
	);
}

function ctsc_metadata_background_styles(){
	return array(
	'Centered' => 'center',
	'Fixed' => 'fixed',
	);
}

function ctsc_metadata_background_positions(){
	return array(
	'Centered' => 'center',
	'Top' => 'center top',
	'Right' => 'right center',
	'Bottom' => 'center bottom',
	'Left' => 'left center',
	'Right Top' => 'right top',
	'Right Bottom' => 'right bottom',
	'Left Bottom' => 'left bottom',
	'Left Top' => 'left top',
	);
}

function ctsc_metadata_background_sizes(){
	return array(
	'Cover Entire Row' => 'cover',
	'Contain Inside Row' => 'contain',	
	'Normal Size' => 'auto',
	);
}

function ctsc_metadata_text_color(){
	return array(
	'Light Scheme' => 'light',
	'Dark Scheme' => 'dark',
	);
}